#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_v1:
  resource: '../src/Controller/Api/V1'
  type:     annotation
  prefix:   '/api/v1/'
  defaults:
    _format: json